-- Predictions tablosundaki tüm verileri sil
TRUNCATE TABLE predictions RESTART IDENTITY CASCADE;

-- Seed data for predictions table - Temiz veri
INSERT INTO predictions (
  title,
  description,
  category,
  created_by,
  target_date,
  status,
  technical_analysis,
  emotional_analysis,
  total_xlm_staked,
  supporting_xlm,
  opposing_xlm,
  success_rate,
  probability,
  odds
) VALUES
-- VALORANT BAHİSLERİ
(
  'Valorant Patch 9.0: Yeni Ajan Meta''yı Değiştirir Mi?',
  'Gelecek patch''da eklenen yeni ajan pick rate %20''yi geçer mi?',
  'valorant',
  'ProsanalystXYZ',
  NOW() + INTERVAL '7 days',
  'active',
  'Oyunda benzer ajan türlerinin istatistiklerine bakıldığında, ajan pick rate %15 civarında olacağı öngörülüyor.',
  'Pro oyuncuların yorumlarına göre, Valorant geliştirme ekibi oyunun meta''sını shake up etmek istiyor.',
  2500,
  1800,
  700,
  85,
  78,
  1.45
),
(
  'VCT Americas: Sentinels vs Cloud9 - Kim Kazanır?',
  'VCT Americas maçında Sentinels Cloud9''u yener mi?',
  'valorant',
  'ValorantGuru',
  NOW() + INTERVAL '2 hours',
  'active',
  'Sentinels son 5 maçta 4 galibiyet aldı. Cloud9 ise son dönemde formunu kaybetti.',
  'Taraftar desteği ve ev sahibi avantajı Sentinels''a psikolojik üstünlük sağlıyor.',
  8500,
  5100,
  3400,
  75,
  62,
  1.65
),
(
  'Valorant: Jett Nerf Gelecek Mi?',
  'Bir sonraki patch''te Jett''e nerf gelir mi?',
  'valorant',
  'AgentAnalyst',
  NOW() + INTERVAL '14 days',
  'active',
  'Jett pick rate %35 ve win rate %54. Riot genelde bu tür istatistiklerde nerf yapar.',
  'Topluluk Jett''in çok güçlü olduğunu düşünüyor, Riot muhtemelen dinleyecek.',
  3200,
  2400,
  800,
  80,
  72,
  1.38
),

-- LEAGUE OF LEGENDS BAHİSLERİ
(
  'LoL: Support Rolü Zayıflatılacak Mı?',
  'Yeni balance patch''ta support damage''ı düşecek mi?',
  'lol',
  'MetaAnalyzer88',
  NOW() + INTERVAL '14 days',
  'active',
  'Son 3 patch''ta support damage arttı ve win rate %52 oldu. Genellikle meta-defining roller her season zayıflatılıyor.',
  'Riot Games CEO''su, supp oyuncu deneyimini artırmak istediğini söyledi.',
  1850,
  950,
  900,
  72,
  55,
  1.82
),
(
  'LCK Winter: T1 vs Gen.G - Şampiyon Kim?',
  'LCK Winter finalinde T1 Gen.G''yi yener mi?',
  'lol',
  'KoreanHype',
  NOW() + INTERVAL '4 hours',
  'active',
  'T1 Faker liderliğinde son 3 seride Gen.G''yi yendi. Ancak Gen.G yeni roster ile güçlü.',
  'Faker efsanesi ve T1 mirası, takıma motivasyon sağlıyor.',
  12500,
  7500,
  5000,
  88,
  58,
  1.72
),
(
  'LoL Worlds 2025: Hangi Bölge Şampiyon?',
  'Worlds 2025''te LCK takımı mı LPL takımı mı şampiyon olur?',
  'lol',
  'WorldsOracle',
  NOW() + INTERVAL '180 days',
  'active',
  'Son 5 yılda LCK 3, LPL 2 şampiyonluk kazandı. Şu an LCK daha güçlü görünüyor.',
  'Taraftar oylamasında %60 LCK favori.',
  25000,
  15000,
  10000,
  65,
  60,
  1.67
),

-- CS2 BAHİSLERİ
(
  'ESL Pro League: FaZe vs Navi - Maç Sonucu',
  'ESL Pro League''de FaZe Clan Navi''yi 2-0 yener mi?',
  'cs2',
  'CS2Prophet',
  NOW() + INTERVAL '1 hour',
  'active',
  'FaZe son 5 maçta 3 galibiyet aldı. Navi ise s1mple dönüşüyle güçlendi.',
  'FaZe taraftarları yoğun destek veriyor, ev sahibi avantajı var.',
  9800,
  4900,
  4900,
  70,
  48,
  2.08
),
(
  'IEM Katowice 2025: G2 Şampiyon Olur Mu?',
  'IEM Katowice 2025''te G2 Esports şampiyonluğa ulaşır mı?',
  'cs2',
  'KatowiceKing',
  NOW() + INTERVAL '5 days',
  'active',
  'G2 son 2 büyük turnuvada final oynadı. Form grafiği yukarı yönlü.',
  'NiKo ve m0nesy ikilisi motivasyon zirvesinde.',
  6500,
  3900,
  2600,
  78,
  35,
  2.85
),
(
  'CS2: AWP Nerf Gelecek Mi?',
  'CS2''de AWP''ye hareket veya hasar nerfü gelir mi?',
  'cs2',
  'WeaponMaster',
  NOW() + INTERVAL '30 days',
  'active',
  'AWP pick rate pro maçlarda %95. Valve genelde dominant silahları dengeler.',
  'Topluluk AWP''nin dengeli olduğunu düşünüyor, nerf gelmeyebilir.',
  4200,
  1680,
  2520,
  62,
  40,
  2.50
),

-- DOTA 2 BAHİSLERİ
(
  'Dota 2 TI 2025: Hangi Ülke Şampiyon?',
  'The International 2025''te hangi bölge şampiyon olur?',
  'dota2',
  'ESportsProphet',
  NOW() + INTERVAL '60 days',
  'active',
  'Geçmiş 5 yıl TI verilerine bakıldığında, Çin ve Avrupa ekipleri %70 başarı oranına sahip.',
  'Esports analitik ekipleri, bu yıl Güney Kore ekiplerinin comeback yapabileceğini tahmin ediyor.',
  5200,
  3200,
  2000,
  68,
  65,
  1.54
),
(
  'DPC 2025: Team Spirit vs Gaimin - Kim Kazanır?',
  'DPC 2025 maçında Team Spirit Gaimin Gladiators''ı yener mi?',
  'dota2',
  'DotaOracle',
  NOW() + INTERVAL '3 hours',
  'active',
  'Team Spirit TI13 şampiyonu ve formda. Gaimin ise yeni patch''e adapte olmakta zorlanıyor.',
  'Spirit''in şampiyonluk deneyimi psikolojik avantaj sağlıyor.',
  7800,
  5460,
  2340,
  82,
  70,
  1.43
),
(
  'Dota 2: Yeni Hero OP Olacak Mı?',
  'Dota 2''de eklenecek yeni hero ilk haftada %55+ win rate''e ulaşır mı?',
  'dota2',
  'HeroHunter',
  NOW() + INTERVAL '45 days',
  'active',
  'Son eklenen 3 hero ilk haftada %52-58 arası win rate gösterdi.',
  'Valve yeni heroleri güçlü çıkarma eğiliminde.',
  3500,
  2100,
  1400,
  75,
  60,
  1.67
),

-- TFT BAHİSLERİ
(
  'TFT Set 12: En Güçlü Comp Hangisi?',
  'TFT Set 12''de Reroll comp''lar meta''yı domine eder mi?',
  'tft',
  'TFTMaster',
  NOW() + INTERVAL '21 days',
  'active',
  'Set 11''de reroll comp''lar %35 play rate''e ulaştı. Set 12 mekanikler benzer.',
  'Challenger oyuncular reroll meta''sından şikayet ediyor, nerf gelebilir.',
  2800,
  1680,
  1120,
  70,
  58,
  1.72
),
(
  'TFT Worlds: Kore Şampiyon Olur Mu?',
  'TFT Dünya Şampiyonası''nda Kore temsilcisi şampiyon olur mu?',
  'tft',
  'TacticianKR',
  NOW() + INTERVAL '90 days',
  'active',
  'Son 3 TFT Worlds''te Kore 2 şampiyonluk kazandı. Ladder''da Koreli oyuncular dominant.',
  'Kore TFT topluluğu çok aktif ve rekabetçi.',
  4500,
  3150,
  1350,
  85,
  68,
  1.47
);
